### PR TITLE
first try

### PR DESCRIPTION
**Pull request by EctoOne**
I'm done with the first version.
Like I mentioned on the forum, you need to make your svg logos white (ffffff), then I had some troubles with the indicator. The svg was vertical but the png with the single dot was horizontal, I wasn't able to align them correctly for now.
It is very important that your character images have the same dimension as the neogeo one, otherwise they will probably not fit in the box or overlap.
As for sorting new system files:
character images go into _assets/characters/
logo images go into _assets/logos/
controller images go into _assets/controllers/
indicator images go into _assets/indicators/
Very Important: Every image for a new system needs to have the same name when you move them into the dedicated folder. Example: If you add Game Gear, every image must be gamegear with the correct extension. That's why i added the _assets/_systemnames/ folders to show you what the correct names are. You can delete the folder afterwards.
As for the system texts, you need can copy any of the included folder (I added those I already made based of your old version), rename it to the system you want (again, look at the _systemnames folder to get the right name), then edit both text lines in the copied theme.xml in the new folder.

Another thing I had some troubles with, was the linespacing on the gamelist. I got it right on my windows version, but it was wrong when I tested it on my Pi. It should look fine now.

### CODE REVIEW

**Comment by chicueloarcade** [comment]
Great I understand the structure and the naming file system. That was clear at once

The game indicator that was horizontal its not the system indicator, it was a blue dot that indicates the game you are selecting. When I make the theme I use one png from another theme that was that size, Recently I Croped the unused area.
I updated the fork and now you will see a blue dot called game-indicator.png in the art folder. That is a global image for the game lists.

The line spacing on the game list, you can use the tag I place you on the Theme guidelines.txt, that worked for me on my PI. (1.62 instead 1.71 line spacing)

The character images MUST be the same size thats right, I planed that from the beginning, but controller png can be different size?

I will try this files and then Ask you in case I found something that doesn't fit.
Thanks!

**Comment by EctoOne** [comment]
Oh I see, I got the indicators mixed up and used the icon.png from your original version.

I tried 1.62 as line spacing when I tested it on my Pi and it was off. I'm not sure why that is.

Yeah, the controller images can have different sizes. They are aligned to the bottom right corner, although now that I think of it, I should center it at the bottom left corner of the character image. If I keep it like it is now, for example the game boy image might be to close to the edges of the screen and look weird. I'll look into that tomorrow.

**Comment by chicueloarcade** [comment]
Thank you very much! Im working on styling the text sizes, width of them, number of lines and visual aspects. Try and error.
The only things I can't achieve now is the indicator on the game list that is stretched, the logos color that its showing black and the transition between logos has a little animation that I want to remove.
Also the indicator of the system is not showing up (I remove the comment and use a png file)

Out of that its going great, Tomorrow I send you the new files to try!

**Comment by EctoOne** [comment]
Have you replaced the gamelist indicator with the new file? It worked for me when I was using the one from the old version. I'll look into that.
The logos are black because they are not white svgs, they should be grey (unless I forget to add a color tag). Like I said, svg support is a little bit bugged.
What animation do you mean? You can only select the carousel transitions in the options, there is no way to do anything related to animations with the theme.
As for the system indicator, have you changed the extension in the theme.xml as well? Otherwise it will simply not find it.

**Comment by chicueloarcade** [comment]
I solved the game list icon by using the original one, I assume it has to be the same with as the game list text. Now its working fine.

The logos are white, I don't know why are they showing 100% black, its a mystery

When you change from one system yo another all the assets are in the same place, except for the logos that make a vertical transition (my ui settings for the transitions is instant)

The system indicator I did not changed on the other xml, but I have 2 tags for this in the main xml.
Should I delete the first  <image> wich calls a indicator-base.svg? This is no longer a file


One thing I am noticing now is that when I quit a game, I se a strange behavior before returning to the theme, like some stars (I assume rating ones) appear for a fraction of time and disappear.

In case I can't solve some issues I will send you a video.

Thanks for the big help!

**Comment by EctoOne** [comment]
Maybe I missed something regarding the colors, I'll check it out.
Same with the transition, maybe I can complety remove the carousel function and use the same method to display the logo that I used on the gamelist. Maybe that will also fix the color issues. Are the logos on the gamelist black too?
There are two tags of the system indicator because I thought the svg was used to show how many systems you have and the png was only used as overlay to indicate which system is active. I can't remember if both entries have the same positions set, but I suggest keeping the one with the indicator-base name and delete the second.
For the popup of the stars, I guess that's because they use the default values. I didn't even know that nowadays elements will not show up if there is no value assigned to them. Seems like it's not perfect, so the best way would be to use the old method to hide them by moving them of screen. I can simply do that by copying a code block from my personal theme.
But now I'm going to bed, it's already almost 3am here. :)

**Comment by EctoOne** [comment]
Oh, and can you accept the pull request? It will copy my changes to your repository, and when you use the github app on your pc you can download the updated version. Then you can edit those files, upload the changes and I can get those updates then. This will prevent us from working on multiple versions without knowing what the other one did.

**Comment by chicueloarcade** [comment]
I solved the logo transition, it was on the GUI menu.
But they still display black, in both in game and main menu.

For the indicator I tried to make the global and the white dot but no luck, I moved arround the screen cause I thought it was hidden under other element by the z index but did not work.

There are minor things to fix, I think the last retropie update is a little bit buggy.

Sorry but I don't understand how to do the pull request, what I did was download your files, unzip and then work over there. If you want I can update my repo so you see this files.

Im going to bed too. Tomorrow we keep talking, I have no hurry so if you want to take your time its more than ok!

**Comment by EctoOne** [comment]
I have no idea how to accept the pull request either, I've only send them to fix some themes in the past. And since I never released anything big myself, I never got one.
As long as we don't work on the files at the same time it should be fine if we just download each other's changes.

**Comment by EctoOne** [comment]
Looks like you already changed some of the things I mentioned.
I got the system indicator to show up, must have been a position conflict from the previous svg settings.
And I also added the Hidden Elements Codeblock, I hope that fixes the pop ups you've seen.

As for the logo colors, it actually seems to be a problem with your svgs. I tried using your files in a different theme where I knew the color tag worked, and they were black. I added the scummvm.svg from another theme into the logos folder and it works. So maybe I was wrong that you have to use white svg at all, but I have no idea. I uploaded the scummvm.svg along with the updated theme.xml, maybe you can compare them (all i can remember is that EmulationStation either doesn't support stroke svg or only stroke svg. Something like that, not sure tho). If you can't figure it out by yourself, just search the forum or ask.

Anyways, looks like my work is pretty much done. It was fun, and I learned a thing or two. :D

**Comment by chicueloarcade** [comment]
Hey, everything is working fine now! the indicator and the svg file. I only use expanded vector so I should work, maybe the svg export version. I will place all the logos in the scummvm file and save with that preset.
Also the rating stars aren't showing un now.
You are great! really, I am very thankful for your help!

One last question, did you know how to upload the theme to emulation station menu?
Thank you very much again!

**Comment by chicueloarcade** [comment]
I found what was troubling the svg files, I am using adobe CC and it saves the svg in a slightly different format than older versions, so I have to change some settings.
Now it works great

**Comment by EctoOne** [comment]
Glad to hear that you got it sorted out.
As far adding your theme to Retropie, I'm not sure. I know that your repository must be named 'es-theme-YOURTHEMENAME'. Since you got the most things fixed, it would be the best to create a new repository with that specific name and upload your files.
Then you have to fork https://github.com/RetroPie/RetroPie-Setup with a browser and then use the desktop app to download (clone) that repository to your pc.
Then edit: RetroPie-Setup/scriptmodules/supplementary/esthemes.sh

Add your theme by adding 'yourgithubname yourthemename(without the es-theme part)' some around line 50. Example: 'chicueloarcade chicuelo'
Then upload the file using the desktop app, and select pull request from one of the menus. I think it will open a webpage where you have to add a description and stuff. After that there is a create pull request on the page that you have to click. If everything was done correctly, you have to wait until your pull request gets accepted.
If you never want create a theme again, you can delete every repository from your account except the 'es-theme-YOURTHEMENAME' one, because that is the source of your theme then.
If your pull request gets accepted, you can update your theme by uploading new/changed files to your 'es-theme-YOURTHEMENAME' repository, and the user have to re-download it from the Retropie menu.

**Comment by chicueloarcade** [comment]
Ohh great! sounds very tricky but I will Try!
Thank you very much and if you need anything and I can do it just ask.
Have a nice day!

**Pull request closed without merging**
